AnalysisType: rule
DedupPeriodMinutes: 180
Description: >-
  Checks for errors during S3 Object access. This could be due to insufficient access
  permissions, non-existent buckets, or other reasons.
DisplayName: "AWS S3 Access Error"
Enabled: true
Filename: aws_s3_access_error.py
LogTypes:
  - AWS.S3ServerAccess
Reference: https://docs.aws.amazon.com/AmazonS3/latest/dev/ErrorCode.html
Reports:
  MITRE ATT&CK:
    - TA0007:T1619
RuleID: "AWS.S3.ServerAccess.Error"
Runbook: >-
  Investigate the specific error and determine if it is an ongoing issue that needs
  to be addressed or a one off or transient error that can be ignored.
Severity: Info
SummaryAttributes:
  - bucket
  - key
  - requester
  - remoteip
  - operation
  - errorCode
Tags:
  - AWS
  - Security Control
  - Discovery:Cloud Storage Object Discovery
Tests:
  - ExpectedResult: false
    Log:
      "authenticationtype": "AuthHeader"
      "bucket": "cloudtrail"
      "bucketowner": "2c8e3610de4102c8e3610de4102c8e3610de410"
      "bytessent": 9438
      "ciphersuite": "ECDHE-RSA-AES128-SHA"
      "errorcode": "SignatureDoesNotMatch"
      "hostheader": "cloudtrail.s3.us-west-2.amazonaws.com"
      "hostid": "2c8e3610de4102c8e3610de4102c8e3610de410"
      "httpstatus": 403
      "key": "AWSLogs/o-3h3h3h3h3h/123456789012/CloudTrail/us-east-1/2020/06/21/123456789012_CloudTrail_us-east-1_20200621T2035Z_ZqQWc4WNXOQUiIic.json.gz"
      "operation": "REST.PUT.OBJECT"
      "remoteip": "54.159.198.108"
      "requestid": "8EFD962F22F2A510"
      "requesturi": "PUT /AWSLogs/o-wyibehgf3h/123456789012/CloudTrail/us-east-1/2020/06/21/123456789012_CloudTrail_us-east-1_20200621T2035Z_ZqQWc4WNXOQUiIic.json.gz
        HTTP/1.1"
      "signatureversion": "SigV4"
      "time": "2020-06-21 20:41:25.000000000"
      "tlsVersion": "TLSv1.2"
      "totaltime": 9
      "useragent": "aws-internal/3"
    Name: Amazon Access Error
  - ExpectedResult: true
    Log:
      "bucket": "panther-auditlogs"
      "errorcode": "AccessDenied"
      "httpstatus": 403
      "operation": "REST.GET.OBJECT"
      "remoteip": "10.106.38.245"
      "requester": "arn:aws:iam::162777425019:user/awslogsdelivery"
      "requestid": "5CDAB4038253B0E4"
      "time": "2020-04-22 07:48:45.000"
      "tlsversion": "TLSv1.2"
    Name: Access Error
  - ExpectedResult: false
    Log:
      "bucket": "panther-auditlogs"
      "errorcode": "InternalServerError"
      "httpstatus": 403
      "operation": "REST.HEAD.BUCKET"
      "remoteip": "10.106.38.245"
      "requester": "arn:aws:iam::162777425019:user/awslogsdelivery"
      "requestid": "5CDAB4038253B0E4"
      "time": "2020-04-22 07:48:45.000"
      "tlsversion": "TLSv1.2"
    Name: 403 on HEAD.BUCKET
  - ExpectedResult: false
    Log:
      "bucket": "panther-auditlogs"
      "errorcode": "InternalServerError"
      "httpstatus": 500
      "operation": "REST.HEAD.BUCKET"
      "remoteip": "10.106.38.245"
      "requester": "arn:aws:iam::162777425019:user/awslogsdelivery"
      "requestid": "5CDAB4038253B0E4"
      "time": "2020-04-22 07:48:45.000"
      "tlsversion": "TLSv1.2"
    Name: Internal Server Error
Threshold: 5
